---
- hosts: all
  gather_facts: yes
  become: yes
  tasks:
  - name: Install Apache HTTP server on RedHat Server
    yum:
      name: httpd
      state: present
    when: ansible_os_family == "RedHat"
  - name: start httpd
    service:
     name: httpd
      state: started


  - name: Install Apache HTTP server on Ubuntu server
    apt:
      name: apache2
      state: present
    when: ansible_os_family == "Debian"

  handlers:
  - name: start in ubuntu
    service:
      name: apache2
      state: started
      enabled: yes
